---

- name: Install common desktop packages
  become: yes
  apt:
    pkg:
      - git
      - curl
#      - lsd
#      - bat
#      - duf
#      - dust

- name: Remove python2 (minimal)
  become: yes
  apt:
    pkg: python2.7-minimal
    state: absent

