---
- name: Create /opt/golang
  ansible.builtin.file:
    path: /opt/golang/{{ golang_version }}
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Download golang
  get_url:
    url: https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz
    checksum: sha256:d3379c32a90fdf9382166f8f48034c459a8cc433730bc9476d39d9082c94583b
    dest: /opt/golang

- name: Extract golang
  ansible.builtin.unarchive:
    src: /opt/golang/go{{ golang_version }}.linux-amd64.tar.gz
    dest: /opt/golang/{{ golang_version }}


- name: Link new golang version
  ansible.builtin.file:
    src: /opt/golang/{{ golang_version }}
    dest: /opt/golang/current
    force: yes
    state: link