---
- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: desktop_user

- debug: var=desktop_user

# This keep changing the clone directory to root ownership
#- name: Clone pyenv to HOME/.pyenv
#  become: no
#  ansible.builtin.git:
#    repo: https://github.com/pyenv/pyenv.git
#    dest: "{{ ansible_env.HOME }}/.pyenv"

- name: Create HOME/bashrc.d
  become: yes
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bashrc.d"
    state: directory
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    mode: '0755'

- name: Create system /etc/bashrc.d
  become: yes
  ansible.builtin.file:
    path: /etc/bashrc.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create pyenv system plugin
  become: yes
  template:
    src: templates/pyenv-pipenv.sh
    dest: /etc/bashrc.d/pyenv-pipenv.sh
    owner: root
    group: root
    mode: '0644'

- name: Create go system plugin
  become: yes
  template:
    src: templates/golang.sh
    dest: /etc/bashrc.d/golang.sh
    owner: root
    group: root
    mode: '0644'


- name: Create HOME/.bashrc.local
  become: yes
  ansible.builtin.template:
    src: templates/bashrc.local
    dest: "{{ ansible_env.HOME }}/.bashrc.local"
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    mode: '0644'


- name: Link /etc/bashrc.d/golang.sh to HOME/bashrc.d/golang.sh
  become: yes
  ansible.builtin.file:
    src: "/etc/bashrc.d/golang.sh"
    dest: "{{ ansible_env.HOME }}/bashrc.d/golang.sh"
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    state: link


- name: Link /etc/bashrc.d/pyenv-pipenv.sh to HOME/bashrc.d/pyenv-pipenv.sh
  become: yes
  ansible.builtin.file:
    src: "/etc/bashrc.d/pyenv-pipenv.sh"
    dest: "{{ ansible_env.HOME }}/bashrc.d/pyenv-pipenv.sh"
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    state: link

- name: Update bashrc to call bashrc.local
  become: yes
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: ". source $HOME/.bashrc.local"
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"


- name: Install packages required by pyenv to install python
  become: yes
  apt:
    pkg:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
