---
- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: desktop_user

- debug: var=desktop_user

- name: Create HOME/bashrc.d
  become: no
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bashrc.d"
    state: directory
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    mode: '0755'

- name: Create system /etc/bashrc.d
  become: yes
  ansible.builtin.file:
    path: /etc/bashrc.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create pyenv system plugin
  become: yes
  template:
    src: templates/pyenv-pipenv.sh
    dest: /etc/bashrc.d/pyenv-pipenv.sh
    owner: root
    group: root
    mode: '0644'

- name: Create go system plugin
  become: yes
  template:
    src: templates/golang.sh
    dest: /etc/bashrc.d/golang.sh
    owner: root
    group: root
    mode: '0644'


- name: Create HOME/.bashrc.local
  become: no
  ansible.builtin.template:
    src: templates/bashrc.local
    dest: "{{ ansible_env.HOME }}/.bashrc.local"
    owner: "{{ desktop_user.stdout }}"
    group: "{{ desktop_user.stdout }}"
    mode: '0644'