
---
- name: Install Go and Hugo
  become: no
  hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    desktop_user: nate
    golang_version: 1.15.8
  roles:
#    - darkwizard242.hugo
#    - golang
    - shell